parameters:
  jsend_standard.response_factory.class: JsendStandard\Factory\ResponseFactory

services:
  jsend_standard.response_factory:
    class: "%jsend_standard.response_factory.class%"
    public: true
    autowire: true
