parameters:
  jsend_standard.response_factory.class: JsendStandard\Factory\ResponseFactory

services:
  JsendStandard\Factory\ResponseFactory:
    class: "%jsend_standard.response_factory.class%"
    public: true
    autowire: true
